export const enigmes = {
  1: {
    password: null,
    text: "<p>Devant vous, une flaque de sang fraîchement répandue. Quelqu’un y a tracé des lettres, mais elles semblent n’avoir aucun sens. La perte de sang lui aurait-elle fait perdre la raison ?</p>",
    imageName: "c5ad6bff-83f8-46d8-b227-83832d3f0c5a",
    solutions: ["Aidez-moi"],
    successText:
      "<p>En prenant un peu de recul, vous remarquez de minuscules éclaboussures de sang qui s'éloignent de la flaque. Elles forment une piste discrète, menant jusqu’à la machine à pH située au premier étage.</p>",
  },
  2: {
    password: "488",
    text: "<p>Près de la machine, vous découvrez un grimoire rempli de formules et de textes incohérents, dépourvus de sens. Cependant, une page en particulier attire votre attention. Elle semble légèrement plus lisible que les autres, sans pour autant l’être totalement. Le poème qui y figure vous paraît étrange, comme s’il dissimulait une signification cachée.</p>",
    imageName: "81490372-bf9d-45be-b817-295d722c08ab",
    solutions: ["Terminal"],
    successText:
      "<p>&quot;Terminal ? Qu'est-ce que cela peut bien signifier ?&quot; Vous vous plongez &agrave; nouveau dans le grimoire, mais soudain, vous r&eacute;alisez que la derni&egrave;re page a &eacute;t&eacute; arrach&eacute;e ! La page terminale du grimoire ! Quelqu'un a d&ucirc; la voler ! Il est imp&eacute;ratif de la retrouver.<br />Pris de panique, vous vous lancez dans une fouille fr&eacute;n&eacute;tique &agrave; travers toute la maternit&eacute;. Vous passez chaque &eacute;tage en revue, m&eacute;thodiquement, jusqu&rsquo;&agrave; atteindre le dernier. Mais rien&#8230; Vous ne trouvez aucune trace de la page disparue.<br />Epuis&eacute; et d&eacute;shydrat&eacute;, vous d&eacute;cidez de faire une pause pour boire un grand verre d'eau, juste &agrave; c&ocirc;t&eacute; de l'endroit o&ugrave; vous avez interrompu vos recherches. Vos yeux, perdus dans le vide, s&rsquo;arr&ecirc;tent soudain sur un petit bout de papier gisant pr&egrave;s du frigo. En vous approchant, vous r&eacute;alisez avec stupeur que c'est la page manquante du grimoire !<br /></p>",
  },
  3: {
    password: "923",
    text: "<p>La page est abîmée, noircie par endroits, mais une formule reste encore lisible.</p>",
    imageName: "c7556498-9f96-4ad1-8b57-23df338f41a1",
    solutions: ["AU", "79"],
    successText:
      "<p>Auriez-vous d&eacute;couvert la formule que les alchimistes cherchent depuis des si&egrave;cles ? Celle qui permet de cr&eacute;er de l&rsquo;or ? C&rsquo;est tout simplement incroyable ! Extraordinaire !<br />Mais avant de r&eacute;v&eacute;ler cette d&eacute;couverte au monde, vous devez la tester. Sans perdre une seconde, vous retournez &agrave; la maternit&eacute; pour pr&eacute;parer votre potion.<br />Vous commencez par faire fondre du cuivre et du fer, puis vous plongez le tout dans un bain de chlore, suivi d&rsquo;un bain d&rsquo;azote liquide pour refroidir le m&eacute;lange. Soudain, une fum&eacute;e verte envahit la pi&egrave;ce, &eacute;paisse et suffocante. Elle vous prend &agrave; la gorge et vous br&ucirc;le les yeux. Pris de panique, vous courez jusqu'au balcon pour respirer un peu d&rsquo;air frais.<br />Mais la douleur dans vos yeux persiste. En retournant &agrave; l'int&eacute;rieur, vous remarquez que la porte de la salle de staff est grande ouverte. Sur l'un des murs, une phrase est apparue, grav&eacute;e myst&eacute;rieusement&#8230; une phrase que vous n&rsquo;aviez jamais vue auparavant.<br /></p><p>Auriez-vous d&eacute;couvert la formule que les alchimistes cherchent depuis des si&egrave;cles ? Celle qui permet de cr&eacute;er de l&rsquo;or ? C&rsquo;est tout simplement incroyable ! Extraordinaire !<br />Mais avant de r&eacute;v&eacute;ler cette d&eacute;couverte au monde, vous devez la tester. Sans perdre une seconde, vous retournez &agrave; la maternit&eacute; pour pr&eacute;parer votre potion.<br />Vous commencez par faire fondre du cuivre et du fer, puis vous plongez le tout dans un bain de chlore, suivi d&rsquo;un bain d&rsquo;azote liquide pour refroidir le m&eacute;lange. Soudain, une fum&eacute;e verte envahit la pi&egrave;ce, &eacute;paisse et suffocante. Elle vous prend &agrave; la gorge et vous br&ucirc;le les yeux. Pris de panique, vous courez jusqu'au balcon pour respirer un peu d&rsquo;air frais.<br />Mais la douleur dans vos yeux persiste. En retournant &agrave; l'int&eacute;rieur, vous remarquez que la porte de la salle de staff est grande ouverte. Sur l'un des murs, une phrase est apparue, grav&eacute;e myst&eacute;rieusement&#8230; une phrase que vous n&rsquo;aviez jamais vue auparavant.<br /></p>",
  },
  4: {
    password: "962",
    text: "<p>Vous attrapez une de vos coll&egrave;gues au vol, votre c&#339;ur battant &agrave; tout rompre, et l'entra&icirc;nez vers le mur pour lui montrer la phrase grav&eacute;e. &quot;Regarde, c&rsquo;est l&agrave; ! Juste ici !&quot; dites-vous, la voix tremblante. Mais &agrave; votre grande stupeur, elle fronce les sourcils. &quot;De quoi tu parles ? Il n&rsquo;y a rien l&agrave;&#8230;&quot;<br /> Le doute vous envahit. La fum&eacute;e vous aurait-elle fait halluciner ? Pourtant, vous regardez de nouveau, et la phrase est toujours l&agrave;, grav&eacute;e dans le mur, aussi claire que possible. Mais ce qui est &eacute;crit semble n&rsquo;avoir aucun sens. Des mots &eacute;tranges, imbriqu&eacute;s de mani&egrave;re incompr&eacute;hensible, comme un puzzle cryptique que seul vous pouvez voir.<br /> Votre coll&egrave;gue vous lance un regard inquiet. &quot;Tu devrais peut-&ecirc;tre te reposer.&quot; Mais vous savez ce que vous avez vu. Cette phrase, m&ecirc;me insens&eacute;e, semble vous appeler. Pourquoi personne d&rsquo;autre ne peut la percevoir ? Est-ce une illusion, ou pire, un avertissement ?<br /> La sensation d&rsquo;&ecirc;tre seul face &agrave; cette &eacute;nigme vous serre la poitrine. Et si cette phrase, apparemment d&eacute;nu&eacute;e de sens, dissimulait un message crypt&eacute;, quelque chose d'essentiel ? Vous passez votre main sur le mur, esp&eacute;rant que le contact dissipera le myst&egrave;re, mais les mots restent grav&eacute;s, comme fig&eacute;s dans la pierre.<br /> Une pens&eacute;e vous traverse alors l&rsquo;esprit : la phrase cache peut-&ecirc;tre un secret. Un message que seul vous, apr&egrave;s tout ce que vous avez travers&eacute;, &ecirc;tes capable de d&eacute;chiffrer.</p>",
    imageName: "168dd5e6-a7c9-4f36-a8cf-ba14dd607138",
    solutions: ["Hera révèle toi"],
    successText:
      "<p>Lorsque vous prononcez la phrase &agrave; haute voix, une bourrasque de vent se l&egrave;ve soudainement, balay&eacute;e par une force invisible. Les lumi&egrave;res vacillent et dansent comme si elles cherchaient &agrave; &eacute;chapper &agrave; l&rsquo;obscurit&eacute; croissante. Un vent glacial souffle, faisant na&icirc;tre en vous un frisson d&rsquo;inqui&eacute;tude. Les murs eux-m&ecirc;mes semblent vibrer sous cette force myst&eacute;rieuse, et bient&ocirc;t, tout l&rsquo;&eacute;difice tremble dangereusement. La crainte de voir le b&acirc;timent s&rsquo;effondrer vous submerge. Vous vous pr&eacute;cipitez alors vers les escaliers, le c&#339;ur battant. Mais, &agrave; l&rsquo;instant pr&eacute;cis o&ugrave; votre pied touche le sol du rez-de-chauss&eacute;e, tout s&rsquo;arr&ecirc;te. Le calme retombe brutalement, presque assourdissant.<br /> Puis, une &eacute;trange sensation vous attire. Une force semble vous appeler, vous murmurant de la rejoindre. Vos pas vous m&egrave;nent, presque malgr&eacute; vous, vers la porte de la PMA. L&agrave;, dans l&rsquo;embrasure, se tient une silhouette &eacute;th&eacute;r&eacute;e. C&rsquo;est un &ecirc;tre fantomatique qui vous fixe d&rsquo;un regard vide, sans vraiment vous voir, flottant dans cette atmosph&egrave;re entre r&ecirc;ve et cauchemar.<br /> </p>",
  },
  5: {
    password: "327",
    text: "<p>Soudain, la cr&eacute;ature fantomatique tourne lentement son regard vers vous. Ses yeux, vides quelques instants plus t&ocirc;t, s&rsquo;emplissent d&rsquo;une lueur per&ccedil;ante et ancienne. Puis, d&rsquo;une voix profonde et r&eacute;sonnante, elle s&rsquo;adresse &agrave; vous :<br /> &quot;Je suis H&eacute;ra, d&eacute;esse de la maternit&eacute; et gardienne des naissances. Vous avez os&eacute; troubler mon sommeil, mortel, et pour cela, vous ne m&eacute;ritez rien de moins que la mort. Cependant, Ang&eacute;lique est intervenue en votre faveur, adoucissant ma col&egrave;re en affirmant que vous &eacute;tiez son ami.&quot;<br /> Elle marque une pause, vous scrutant de haut en bas, comme pour jauger la v&eacute;rit&eacute; de ces paroles.<br /> &quot;Pourtant, vous ne ressemblez en rien &agrave; un alli&eacute; digne de sa confiance,&quot; poursuit-elle d&rsquo;un ton glacial. &quot;Je vais vous poser une seule question. Si vous donnez la r&eacute;ponse correcte, vous aurez la chance de justifier votre intrusion. Mais si vous &eacute;chouez&#8230; alors vous sombrerez dans un sommeil &eacute;ternel, emprisonn&eacute; dans le monde des r&ecirc;ves jusqu&rsquo;&agrave; la fin des temps.&quot;<br /> La tension est palpable. Chaque mot de la d&eacute;esse semble peser sur vos &eacute;paules comme une sentence imminente, tandis que l&rsquo;air autour de vous devient &eacute;trangement lourd, comme si m&ecirc;me le temps retenait son souffle en attendant votre r&eacute;ponse.<br /> </p>",
    imageName: "732b7353-4e60-4cd3-93ac-3d62b449b4db",
    solutions: ["1759"],
    successText:
      "<p>H&eacute;ra vous fixe intens&eacute;ment, attendant votre r&eacute;ponse. Vous rassemblez votre courage et commencez &agrave; lui raconter tout ce qui vous a amen&eacute; jusqu&rsquo;&agrave; elle : les disparitions myst&eacute;rieuses qui hantent ces lieux depuis des semaines, cette flaque de sang que vous avez d&eacute;couverte, et surtout ce grimoire &eacute;trange aux pages us&eacute;es par le temps. Enfin, vous lui d&eacute;crivez l&rsquo;inscription &eacute;nigmatique grav&eacute;e sur le mur, dont les mots semblaient vibrer d&rsquo;une sombre magie.<br /> &Agrave; mesure que vous parlez, le visage de la d&eacute;esse se ferme, ses traits se crispent, comme si vos paroles r&eacute;veillaient en elle un souvenir qu&rsquo;elle aurait pr&eacute;f&eacute;r&eacute; oublier.<br /> &quot;Oh non, cela recommence...&quot; murmure-t-elle, le regard se perdant dans le vide. Puis, avec une exclamation de frustration, elle reprend : &quot;Je ne peux pas t'en dire davantage, mais je me souviens qu'Ilithyie, la d&eacute;esse de l'enfantement, nous avait pr&eacute;venus de cette sombre histoire il y a bien longtemps. Elle est la seule qui pourrait t'&eacute;clairer davantage sur ce myst&egrave;re.&quot;<br /> H&eacute;ra se redresse, la lueur dans ses yeux s'adoucissant l&eacute;g&egrave;rement.<br /> &quot;Ilithyie aime les lieux en mouvement, elle tra&icirc;ne souvent dans les ascenseurs, fascin&eacute;e par cette &eacute;trange sensation de se d&eacute;placer tout en restant immobile. Elle trouve cela&#8230; apaisant. Je vais lui faire savoir que tu d&eacute;sires la rencontrer.&quot;<br /> D&rsquo;un geste de la main, elle trace un cercle lumineux dans l&rsquo;air. Une vague d&rsquo;&eacute;nergie semble se propager &agrave; travers les murs, traversant l&rsquo;espace comme un message muet envoy&eacute; aux profondeurs du b&acirc;timent. Puis elle vous regarde &agrave; nouveau, une lueur de d&eacute;fi dans le regard.<br /> &quot;Ne la fais pas attendre,&quot; vous avertit-elle d&rsquo;une voix grave. &quot;Elle est bien moins patiente que moi.&quot;<br /> </p>",
  },
  6: {
    password: "147",
    text: "<p>Apr&egrave;s avoir explor&eacute; chaque ascenseur du b&acirc;timent, scrutant chaque recoin et chaque reflet dans les miroirs ternis, vous finissez par la trouver. Une silhouette immobile, drap&eacute;e d'une toge cr&egrave;me, se d&eacute;tache dans le faible &eacute;clairage de la cabine. Ses cheveux blonds tombent en boucles d&eacute;licates autour de son visage serein, contrastant avec ses yeux per&ccedil;ants qui semblent vous sonder d&egrave;s votre arriv&eacute;e.<br /> &quot;H&eacute;ra m&rsquo;a pr&eacute;venue que tu me cherchais,&quot; d&eacute;clare-t-elle d&rsquo;une voix douce, teint&eacute;e d&rsquo;un l&eacute;ger amusement. &quot;Je suis Ilithyie, mais ici, tout le monde m&rsquo;appelle Ily. Que puis-je faire pour toi ?&quot;<br /> Il y a dans ses mots une certaine l&eacute;g&egrave;ret&eacute;, comme si la gravit&eacute; de la situation ne la concernait qu&rsquo;&agrave; demi. Vous vous sentez cependant inexplicablement &agrave; l&rsquo;aise en sa pr&eacute;sence, et, sans d&eacute;tour, vous lui exposez votre inqui&eacute;tude :<br /> &quot;Je cherche &agrave; comprendre ce qui arrive aux sages-femmes qui disparaissent chez nous.&quot;<br /> Le visage d&rsquo;Ily perd soudainement son sourire, et ses traits se tendent sous le poids d&rsquo;un souvenir douloureux. Elle prend une profonde inspiration, semblant lutter pour remettre de l&rsquo;ordre dans ses pens&eacute;es avant de r&eacute;pondre :<br /> &quot;Je&#8230; Je ne peux pas te dire ce qu&rsquo;il se passe,&quot; avoue-t-elle, la voix l&eacute;g&egrave;rement bris&eacute;e. &quot;Il y a quelque temps, Mn&eacute;mosyne, la d&eacute;esse de la m&eacute;moire, m&rsquo;a fait perdre ce savoir &agrave; cause d&rsquo;une querelle idiote entre nous. Depuis, mes souvenirs sont comme des fils enchev&ecirc;tr&eacute;s, des fragments flous qui se perdent dans un brouillard &eacute;pais.&quot;<br /> Elle vous observe avec une lueur d&rsquo;espoir, comme si vous &eacute;tiez peut-&ecirc;tre la cl&eacute; pour restaurer ce qui a &eacute;t&eacute; bris&eacute;.<br /> &quot;Mais,&quot; poursuit-elle lentement, &quot;peut-&ecirc;tre pourrais-tu m&rsquo;aider &agrave; d&eacute;m&ecirc;ler ce chaos. Si nous parvenons &agrave; r&eacute;organiser mes souvenirs, il est possible que nous d&eacute;couvrions ensemble ce qui se cache derri&egrave;re ces disparitions. Accepteras-tu de plonger dans ce labyrinthe de m&eacute;moire avec moi ?&quot;<br /> Ses yeux, brillants d'une lumi&egrave;re int&eacute;rieure, cherchent les v&ocirc;tres avec intensit&eacute;. C'est un appel &agrave; la fois sinc&egrave;re et d&eacute;sesp&eacute;r&eacute;, une pri&egrave;re silencieuse pour retrouver la v&eacute;rit&eacute; enfouie.<br /> </p><p><a href=\"http://www.educol.net/crosswords/l_enquete_d_angelique-0d2d093188ea2f8619c32d8821946011\">Cliquez ici</a> pour remplir l'enigme en ligne</p>",
    imageName: "95e4ba0c-bc8f-48a5-af47-977eeffd6372",
    solutions: ["Enquête"],
    successText:
      "<p>&quot;Est-ce que le mot &lsquo;enqu&ecirc;te&rsquo; vous &eacute;voque quelque chose ?&quot; demandez-vous &agrave; Ilithyie.<br /> &Agrave; votre grande surprise, ses yeux s&rsquo;illuminent soudainement. &quot;Oui !&quot; s&rsquo;&eacute;crie-t-elle. Elle vous explique qu&rsquo;il y a des dizaines d&rsquo;ann&eacute;es, des disparitions similaires de sages-femmes avaient d&eacute;j&agrave; eu lieu. Cela avait conduit les dieux &agrave; envoyer une inspectrice nomm&eacute;e Mahdhi, une sorci&egrave;re d&rsquo;une puissance rare, pour &eacute;lucider ce myst&egrave;re. L&rsquo;enqu&ecirc;te n&rsquo;avait laiss&eacute; qu&rsquo;un seul indice : un grimoire r&eacute;dig&eacute; par le Dr Jean-Louis Baudelocque.<br /> Baudelocque, autrefois un &eacute;minent obst&eacute;tricien, s&rsquo;&eacute;tait mis en t&ecirc;te de combattre une maladie mortelle qui frappait les femmes enceintes, provoquant convulsions et d&eacute;c&egrave;s. Dans sa qu&ecirc;te, il s&rsquo;&eacute;tait rapproch&eacute; de cercles d&rsquo;alchimistes et, &agrave; force d&rsquo;exp&eacute;rimentations, avait maudit la lign&eacute;e de l&rsquo;un de ses confr&egrave;res. Depuis, tous les hommes de cette famille se transforment en b&ecirc;tes &agrave; l&rsquo;&acirc;ge de vingt-et-un ans, attir&eacute;es par l&rsquo;odeur du placenta.<br /> &Agrave; l&rsquo;&eacute;poque, les disparitions passaient inaper&ccedil;ues, car les naissances se d&eacute;roulaient souvent &agrave; domicile. Mais aujourd&rsquo;hui, ces cr&eacute;atures peinent &agrave; atteindre les maternit&eacute;s modernes. C&rsquo;est pourquoi elles errent dans les couloirs &agrave; la recherche de proies, et toute sage-femme qui croise leur chemin dispara&icirc;t myst&eacute;rieusement.<br /> &quot;Mahdhi avait presque r&eacute;solu l&rsquo;affaire,&quot; continue Ilithyie. &quot;Mais sa couverture fut d&eacute;masqu&eacute;e, et elle dut quitter ce monde pr&eacute;cipitamment. Elle a laiss&eacute; l&rsquo;enqu&ecirc;te inachev&eacute;e, et moi&#8230; j&rsquo;ai &eacute;t&eacute; maudite peu apr&egrave;s.&quot;<br /> Elle se penche vers vous, l&rsquo;espoir brillant dans ses yeux. &quot;Peut-&ecirc;tre que ses archives se trouvent encore ici, au premier &eacute;tage, pr&egrave;s de la salle des archives. Cherche l&agrave;-bas. Avec un peu de chance, tu y trouveras des r&eacute;ponses.&quot;<br /> </p>",
  },
  7: {
    password: "311",
    text: "<p>En fouillant dans les archives, votre regard se pose sur une vieille bo&icirc;te poussi&eacute;reuse, oubli&eacute;e au fond d&rsquo;une &eacute;tag&egrave;re. Personne n&rsquo;a d&ucirc; l&rsquo;ouvrir depuis au moins vingt ans. Vous la sortez avec pr&eacute;caution, soufflez sur le couvercle pour chasser la couche de poussi&egrave;re, et l&rsquo;ouvrez lentement.<br /> &Agrave; l&rsquo;int&eacute;rieur, des dossiers jaunis s&rsquo;entassent, couverts de notes griffonn&eacute;es &agrave; la h&acirc;te. Au milieu de ces papiers, un vieil ordinateur portable repose, accompagn&eacute; de son chargeur soigneusement enroul&eacute;. Mais ce qui capte imm&eacute;diatement votre attention, c&rsquo;est un petit post-it coll&eacute; sur le dessus. Aucune inscription dessus, mais des dessins &eacute;tranges. Les motifs, soigneusement trac&eacute;s, &eacute;veillent en vous une &eacute;trange sensation de familiarit&eacute;. Vous sentez qu&rsquo;ils renferment un message ou une cl&eacute;, quelque chose qui pourrait r&eacute;v&eacute;ler bien plus que ce que ces vieux dossiers peuvent raconter.<br /> </p>",
    imageName: "4df65c1b-d269-4ea6-9e24-313cd2507752",
    solutions: ["Sbounan"],
    successText:
      "<p>Vous vous demandez un instant si les symboles trac&eacute;s sur le post-it pourraient &ecirc;tre plus qu&rsquo;un simple gribouillage. Un mot de passe, peut-&ecirc;tre ? Vous entrez la combinaison des dessins en tentant diverses interpr&eacute;tations, et &agrave; votre grande surprise&#8230; &ccedil;a marche. L&rsquo;&eacute;cran s&rsquo;allume, r&eacute;v&eacute;lant un bureau ancien et rudimentaire. D&eacute;cid&eacute;ment, la s&eacute;curit&eacute; informatique d&rsquo;autrefois laissait vraiment &agrave; d&eacute;sirer.<br /> En fouillant dans les fichiers, un dossier attire votre attention : &ldquo;Enqu&ecirc;te d&rsquo;Ang&eacute;lique&rdquo;. Vous l&rsquo;ouvrez imm&eacute;diatement et parcourez les documents qu&rsquo;il contient. Les premi&egrave;res pages ne vous apprennent rien de plus : le dossier a &eacute;t&eacute; &ldquo;class&eacute; sans suite par manque d&rsquo;&eacute;l&eacute;ments&rdquo;. Mais en continuant &agrave; fouiller, vous tombez sur un rapport de l&rsquo;inspectrice Mahdhi. Elle y d&eacute;crit avoir d&eacute;couvert un liquide &eacute;pais et jaun&acirc;tre sur les lieux d&rsquo;une ancienne disparition. Apr&egrave;s analyse, elle avait d&eacute;termin&eacute; que c&rsquo;&eacute;tait du sang&#8230; mais d&rsquo;une esp&egrave;ce inconnue.<br /> Les derniers paragraphes r&eacute;v&egrave;lent que l&rsquo;inspectrice avait tent&eacute; un test ADN. Malheureusement, il n&rsquo;avait pas permis d&rsquo;identifier la cr&eacute;ature, mais elle &eacute;tait convaincue qu&rsquo;il s&rsquo;agissait du sang du monstre lui-m&ecirc;me. Peut-&ecirc;tre avait-il &eacute;t&eacute; bless&eacute; lors de l&rsquo;une de ses chasses ?<br /> Le document se termine par un diagramme &eacute;trange, vous d&eacute;cidez de ne rien laisser au hasard. Vous vous envoyez le document par e-mail pour l&rsquo; imprimer au troisi&egrave;me &eacute;tage pour l&rsquo;&eacute;tudier de plus pr&egrave;s. Vous r&eacute;cup&eacute;rez le papier encore ti&egrave;de qui vient de sortir de l&rsquo;imprimante.<br /> </p>",
  },
  8: {
    password: "024",
    text: "<p>Vous fixez le diagramme. Plus vous l&rsquo;observez, plus il semble vouloir vous parler. Chaque cercle semble s&rsquo;animer sous votre regard, comme si le papier essayait de vous chuchoter un secret.<br /> La fl&egrave;che semble indiquer un mouvement pr&eacute;cis, un parcours &agrave; suivre. Vous plissez les yeux, cherchant &agrave; comprendre. Ce sch&eacute;ma est plus qu&rsquo;un simple dessin. Il essaie de vous guider.<br /> </p>",
    imageName: "488b656f-5aec-4241-9961-de774b3e6d82",
    solutions: ["Il reviendra en 2024"],
    successText:
      "<p>Lorsque vous reliez le dernier cercle du diagramme, un &eacute;clair de lumi&egrave;re jaillit brusquement du papier, vous aveuglant un instant. Vous reculez d&rsquo;un pas, mais il est trop tard : la lumi&egrave;re prend forme, s&rsquo;&eacute;tirant et se d&eacute;formant jusqu&rsquo;&agrave; devenir une surface vaporeuse, semblable &agrave; un miroir flou et tremblotant. L&rsquo;air se charge d&rsquo;une &eacute;nergie surnaturelle. C&rsquo;&eacute;tait ind&eacute;niablement de la magie !<br /> &Agrave; l&rsquo;int&eacute;rieur du miroir, des ombres bougent. Une silhouette se dessine lentement, comme si elle &eacute;mergeait d&rsquo;un brouillard &eacute;pais. Vous retenez votre souffle tandis que la forme se tourne vers vous. Un visage indistinct appara&icirc;t, ses traits masqu&eacute;s par un voile de t&eacute;n&egrave;bres&#8230; et c&rsquo;est alors que vous le remarquez : un liquide &eacute;pais et jaune s&rsquo;&eacute;coule lentement de sa bouche. Du sang ! Du sang jaune ! Exactement comme celui d&eacute;crit dans les notes de l&rsquo;inspectrice.<br /> Votre c&#339;ur s&rsquo;emballe. C&rsquo;est lui, le monstre ! La cr&eacute;ature d&eacute;voreuse de placenta dont parlait le rapport. Soudain, une autre forme &eacute;merge dans l&rsquo;arri&egrave;re-plan, une silhouette indistincte&#8230; humaine ? Vous plissez les yeux pour essayer de discerner ce que c&rsquo;est, mais avant que vous ne puissiez comprendre, le miroir s&rsquo;&eacute;teint brusquement, disparaissant comme une flamme souffl&eacute;e par le vent.<br /> Le silence qui suit est lourd et oppressant.<br /> C&rsquo;est alors que Ilithyie appara&icirc;t, surgissant presque de nulle part, le regard inquiet. &quot;J&rsquo;ai senti une puissante magie,&quot; dit-elle pr&eacute;cipitamment, son visage p&acirc;le et tendu. &quot;Est-ce que tout va bien ? Vous &ecirc;tes livide&#8230; Venez, il faut que vous vous reposiez.&quot;<br /> Sans attendre votre r&eacute;ponse, elle vous prend doucement par le bras et vous entra&icirc;ne vers le deuxi&egrave;me &eacute;tage. &Agrave; peine avez-vous franchi la porte que votre esprit, jusque-l&agrave; embrum&eacute;, se clarifie soudainement. Tout semble plus net, plus limpide. Les pi&egrave;ces s&rsquo;assemblent dans votre t&ecirc;te.<br /> Ce que vous venez de voir n&rsquo;&eacute;tait pas juste une vision. C&rsquo;&eacute;tait un avertissement. Vous comprenez que la cr&eacute;ature est proche&#8230; bien plus proche que vous ne l&rsquo;imaginiez.<br /> </p>",
  },
  9: {
    password: "2000",
    text: "<p>Tout devient clair d&rsquo;un coup. Ce que vous venez de voir&#8230; c&rsquo;&eacute;tait la r&eacute;ponse ! Vous avez enfin compris o&ugrave; se trouve le monstre, ainsi que la date et l&rsquo;heure de sa prochaine apparition. Tous les indices que vous aviez rassembl&eacute;s prenaient sens. Tout &eacute;tait l&agrave;, sous vos yeux, depuis le d&eacute;but !<br /> Il ne vous reste plus qu&rsquo;&agrave; assembler chaque morceau : les mots de passe. Une fois r&eacute;unis, ils vous r&eacute;v&eacute;leront exactement le lieu, la date et l&rsquo;heure o&ugrave; tout doit se passer. Il est temps d&rsquo;agir.<br /> Rassemblez tout le monde. Ce sera votre seule chance de stopper cette cr&eacute;ature et de mettre fin aux disparitions des sages-femmes. Soyez pr&ecirc;ts.<br /> </p>",
    solutions: [],
    successText: "/end",
  },
};
